Vagrant.require_plugin('vagrant-puppet-install')
Vagrant.require_plugin('vagrant-digitalocean')

Vagrant.configure('2') do |config|
  config.puppet_install.puppet_version = :latest

  config.vm.box = 'digital_ocean'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :digital_ocean do |provider, override|
    provider.client_id = ENV['DO_CLIENT_ID']
    provider.api_key = ENV['DO_API_KEY']
    provider.region = 'Amsterdam 1'
    provider.size = '512MB'
    provider.image = 'Ubuntu 12.04.4 x32'
    override.ssh.private_key_path = '~/.ssh/id_rsa'
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = File.expand_path('../../../support/manifests', __FILE__)
    puppet.manifest_file  = "base.pp"
  end
end