name: "Docker Acceptance Tests"
on: [push, pull_request]
jobs:
  docker_acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake test:docker_acceptance